---
- name: Reset canton network
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - group_vars/all.yml
    - group_vars/vault.yml
    - group_vars/{{ env }}.yml

  pre_tasks:
    - name: Include environment setup tasks
      ansible.builtin.include_tasks: tasks/setup_environment.yml

  tasks:
    - name: Include command task
      ansible.builtin.include_tasks: roles/participant/tasks/commands/network_reset.yml
