---
# maintains devnet inventory grouped by project names
all:
  vars:
    env: devnet
  children:
    canton:
      hosts:
        ts.participant.canton.devnet.encapsulate.xyz:
          type: participant
        ts.app.canton.devnet.encapsulate.xyz:
          type: app
        ts.wallet.canton.devnet.encapsulate.xyz:
          type: wallet
        ts.cns.canton.devnet.encapsulate.xyz:
          type: cns
