---
- name: Add Docker repository
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/ubuntu
    suites: "{{ ansible_distribution_release }}"
    components: stable
    architectures: amd64
    signed_by: https://download.docker.com/linux/ubuntu/gpg
    state: present
    enabled: true

- name: Install required packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - openjdk-21-jdk
    - postgresql
    - python3-psycopg2
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Ensure PostgreSQL service is started
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true

- name: Set password for postgres user
  community.postgresql.postgresql_user:
    name: postgres
    password: "{{ postgres.password }}"
    state: present
  become: true
  become_user: postgres
