---
- name: Install postgresql packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - postgresql
    - python3-psycopg2

- name: Ensure PostgreSQL service is started
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true

- name: Set password for postgres user
  community.postgresql.postgresql_user:
    name: postgres
    password: "{{ postgres.password }}"
    state: present
  become: true
  become_user: postgres
