---
# maintains file name, binary names, and anything which is not a directory or path

# config file names
cns_config_file_name: config.js

cns_environment_general_file_name: "{{ service_identifier }}.env"
